// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AuthProvider } from "@/components/theme/auth-provider";
import "./globals.css";
import NavBar from "@/components/Navbar/navBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import SideBar from "@/components/SideBar/orkySideBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// app/layout.tsx

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Opcional: versión PNG para navegadores modernos */}
        <link
          rel="icon"
          href="/assets/images/orky.png"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AuthProvider>
              <div className="flex h-screen w-full">
                {" "}
                {/* 👈 contenedor flex */}
                <SideBar />
                <main className="flex-1 flex flex-col overflow-hidden">
                  <NavBar /> {/* ← dentro del main, arriba */}
                  <div className="flex-1 overflow-auto p-4 md:p-6 border-t-2 border-yellow-600">
                    {children}
                  </div>
                </main>
              </div>
            </AuthProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
